### ISSUE TITLE
Crush after Image Load

### ISSUE THREAD

**Issue by sangmin213** [dguari1/Emotrics#10]
Hi, Thank you for providing facial landmark detecting open source software.

I have a problem that Emotrics(.exe file on dropbox) is terminated after loading image. 
My environment is as follow:
 - Local Python version == 3.9
 - conda virtual environment Python version == 3.5
 - Image size = 27kb
 - Only single image

How can I solve this problem?

**Comment by dguari1** [comment]
Hi, you don't really need to have Python installed if you are using the .exe file. You only need Python (along with the repository requirements) if you want to compile the code yourself. 
I know that Emotrics crashes when loading large images, but that is not the case here. There are a few options that you can try:
1.  Run Emotrics from the command line (cmd) and see if it prints any errors
2. Run the python code directly `python Emotrics.py` and see if you get any errors 
3. Send me the image and I will try it on my side

I no longer have a Windows computer so it is difficult to provide any additional support. 

Thank you for using (or tryin to use) Emotrics!

**Comment by sangmin213** [comment]
Dear Diego,

Hi, thank you for fast replying :)

I took tests in two ways you mentioned as 1) and 2) yesterday.
First, when I run from cmd, *it does not print any errors*. It was same on
both environments with & without python.
And also, I tried on anaconda prompt with virtual environment and its
results was same.

Second, I tried to run python code directly by clone your github repo. But
I cannot know the version of necessary packages(e.g. opencv, numpy ..)
Can I get a requirements.txt for each version of packages?

Sorry for cannot send my data due to security reasons. But it doesn't work
for Heungmin Son's image in Google neither whose size is 30kb.

Sincerely,
Sangmin Han

2023년 8월 8일 (화) 오후 12:36, Diego L. Guarin ***@***.***>님이 작성:

**Comment by dguari1** [comment]
@sangmin213 could you try again using [Emotrics+](https://www.dropbox.com/s/cd2b636xe2hro00/Emotrics%2B%202-22-22.zip?dl=0). The single Image option is very similar to classic Emotrics.

**Comment by dguari1** [comment]
@sangmin213 is Emotrics+ working for you? Please let me know so I can close this issue

**Comment by sangmin213** [comment]
Oh, finally it worked.
Thank you for your hard work :)

2023년 8월 16일 (수) 오전 12:22, Diego L. Guarin ***@***.***>님이 작성:
