### ISSUE TITLE
Request for description adjustment

### ISSUE THREAD

**Issue by mariagrosheva** [dguari1/Emotrics#2]
Dear Developer, 
Due to a recent change in the Medical Devices Act in Europe we cannot use your software for our scientific research anymore. The issue could be resolved by changing the description of your software in your README on GiHub.
The following sentences are causing the regulatory problems (which classifies the Application as a medical device):
"Emotrics works by automatically placing a 68 facial landmarks and using the position of those landmarks to estimate a set of facial measurements that can be used to asses facial symmetry and/or evaluate facial neurumuscular diseases. Moreover, results can be used to compare pre and post-procedure photographs to asses the effectiveness of treatment."

Could you remove the 2nd part in this section, just leaving: "Emotrics works by automatically placing a 68 facial landmarks and using the position of those landmarks to estimate a set of facial measurements that can be used to asses facial symmetry"?
Without any intended medical purpose in the description of Emotrics, the application does not need to be CE certified and can be used in research projects.
Thanks a lot! Regards, Maria Grosheva

**Comment by dguari1** [comment]
Dear Maria

That is a great point. I fixed the description. Please let me know if this works with the current regulations.

**Comment by mariagrosheva** [comment]
Dear Diego!

Thanks you very mich! I´ll let you know about our progress.

Best regards, 

Maria Grosheva

Am 09.06.2021 um 18:46 schrieb Diego L. Guarin ***@***.***>:


Dear Maria

That is a great point. I fixed the description. Please let me know if this works with the current regulations.
