### ISSUE TITLE
Executable Download link broken

### ISSUE THREAD

**Issue by josepest** [dguari1/Emotrics#4]
Hi,

Sorry the executable download link in README is broken.
There is it anywhere available.

Thanks

**Comment by dguari1** [comment]
Hi, thank you for your interest in Emotrics. You can now download Emotrics for Windows from here:
https://www.dropbox.com/s/d9xy43tmosfh69z/Emotrics.zip?dl=0

I also invite you to try our new tool Emotrics +; it includes Emotrics and some additional functionalities. It is still in development
You can download Emotrics+ for widows from here:
https://www.dropbox.com/s/cd2b636xe2hro00/Emotrics%2B%202-22-22.zip?dl=0
