### ISSUE TITLE
Unable to open link

### ISSUE THREAD

**Issue by trahan12** [dguari1/Emotrics#5]
Link isn't working, times out.  Is there an updated or other link.
THanks

**Comment by PSJohn92** [comment]
Where can i download emotrics? for analysis

**Comment by dguari1** [comment]
Hi, thank you for your interest in Emotrics. You can now download Emotrics for Windows from here: 
https://www.dropbox.com/s/d9xy43tmosfh69z/Emotrics.zip?dl=0

I also invite you to try our new tool Emotrics +; it includes Emotrics and some additional functionalities. It is still in development 
You can download Emotrics+  for widows from here: 
https://www.dropbox.com/s/cd2b636xe2hro00/Emotrics%2B%202-22-22.zip?dl=0

**Comment by PSJohn92** [comment]
Thank you for the link to dowmload emotrics.
I am interested in emotrics and facial analysis of facial palsy patients.
May I use emotrics for analysis of patients???

By the way, I am Seong John Han from South Korea.
I am in resident training in plastic surgery of Asan Medical Center, Seoul.

Sincerely, John

**Comment by dguari1** [comment]
Hi @PSJohn92 thank you again for your interest in Emotrics. 
You can use the software to analyze your data; there are many research studies that have done the same. The tool is open-source and free to use. 
I suggest using Emotrics+ as is more accurate and has more options that might be useful. 
https://www.dropbox.com/s/cd2b636xe2hro00/Emotrics%2B%202-22-22.zip?dl=0


If you use Emotrics, or Emotrics+ please cite our work 
Guarin, D. L., Dusseldorp, J., Hadlock, T. A., & Jowett, N. (2018). A machine learning approach for automated facial measurements in facial palsy. JAMA facial plastic surgery, 20(4), 335-337.
