### ISSUE TITLE
Crushing happens

### ISSUE THREAD

**Issue by PSJohn92** [dguari1/Emotrics#6]
Thank you for e-mail with download links.
I downloaded the zip file and extract all the files.
The emotrics.exe launched without problem but when I load images.
The emotrics closed by somewhat reason.

Can I get a solution for it?
I've tried several times but it keep shutting down...

**Comment by dguari1** [comment]
Hi PSJohn92,

This is a known issue with large images (>1MB). You could try:

  1.  Reduce the image size (increase the image compression when saving it)
  2.  Try with Emotrics + -- the single image option is very similar to the regular Emotrics

If that doesn’t work and you are able to share your images, you could send me one of the images so I can try to figure out what is the issue.

Thanks

From: PSJohn92 ***@***.***>
Date: Monday, July 25, 2022 at 4:22 AM
To: dguari1/Emotrics ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dguari1/Emotrics] Crushing happens (Issue #6)

Thank you for e-mail with download links.
I downloaded the zip file and extract all the files.
The emotrics.exe launched without problem but when I load images.
The emotrics closed by somewhat reason.

Can I get a solution for it?
I've tried several times but it keep shutting down...

**Comment by PSJohn92** [comment]
Thanks a lot.
I am going to try with small size photos.

Really thanks a lot.

If you don't mind, may I give you some feedback after applying the Emotrics?

Regards, John

2022년 7월 25일 (월) 오후 11:22, Diego L. Guarin ***@***.***>님이 작성:

**Comment by dguari1** [comment]
Sure, let me know how it goes.

Remember that you don’t want to reduce the image dimensions, you should keep those the same as the original.

Best,

From: PSJohn92 ***@***.***>
Date: Tuesday, July 26, 2022 at 6:49 AM
To: dguari1/Emotrics ***@***.***>
Cc: Diego Guarin Lopez ***@***.***>, Comment ***@***.***>
Subject: Re: [dguari1/Emotrics] Crushing happens (Issue #6)
Thanks a lot.
I am going to try with small size photos.

Really thanks a lot.

If you don't mind, may I give you some feedback after applying the Emotrics?

Regards, John

2022년 7월 25일 (월) 오후 11:22, Diego L. Guarin ***@***.***>님이 작성:

**Comment by PSJohn92** [comment]
Great. I've tried single patient and it worked well.

Sorry for bothering you but in case of auto-eFACE which you also developed,
is it possible to apply the program even if there's less then 8 photos?
Cause sometimes, we don't have puckering or eeee photo for all patients.

If it works without filling all 8 photos, will the measurement value be
effected?

Thank you for your kindness, John

2022년 7월 26일 (화) 오후 9:50, Diego L. Guarin ***@***.***>님이 작성:

**Comment by dguari1** [comment]
Hi again John,

I’m glad that it worked for you.

Auto-eFACE needs all the photos to work. However, you can repeat photos (e.g. add the rest photo in the puckering photo). Just be aware that you won’t be able to use the measurements that need the missing photos.

Please let me know if you need anything else.

Best,

From: PSJohn92 ***@***.***>
Date: Tuesday, July 26, 2022 at 7:33 PM
To: dguari1/Emotrics ***@***.***>
Cc: Diego Guarin Lopez ***@***.***>, Comment ***@***.***>
Subject: Re: [dguari1/Emotrics] Crushing happens (Issue #6)
Great. I've tried single patient and it worked well.

Sorry for bothering you but in case of auto-eFACE which you also developed,
is it possible to apply the program even if there's less then 8 photos?
Cause sometimes, we don't have puckering or eeee photo for all patients.

If it works without filling all 8 photos, will the measurement value be
effected?

Thank you for your kindness, John

2022년 7월 26일 (화) 오후 9:50, Diego L. Guarin ***@***.***>님이 작성:

**Comment by PSJohn92** [comment]
Is emotrics+ more accurate than emotrics? or is it the upgrade version?

Also, I couldn't find the auto-eFace program on your github site.

There's some codes but no exe files...

Am i missing something?

Your advices are really helpful.

I am trying to compare the resting and expression photos.

Thanks, John

2022년 7월 27일 (수) 오전 10:31, Diego L. Guarin ***@***.***>님이 작성:
