### ISSUE TITLE
Missing additional calculations.

### ISSUE THREAD

**Issue by sirtimidg** [dguari1/Emotrics#8]
@dguari1 Add calculations for the nasolabial fold and philtrum.

My students would like this feature.

Thank you.

**Comment by dguari1** [comment]
Hi @sirtimidg, the new version of Emotric: Emotrics +. Emotrics + includes the landmarks around the nasolabial fold and a measure of symmetry based on the nasolabial fold. 
You can download it here: 
[Emotrics+](https://www.dropbox.com/s/cd2b636xe2hro00/Emotrics%2B%202-22-22.zip?dl=0)

The program doesn't do anything related to the philtrum. However, Emotrics + provides a file with the location of the landmarks in the image; you can use those to create your own measurements.
