### ISSUE TITLE
Function of a tool

### ISSUE THREAD

**Issue by misaTes** [dguari1/Emotrics#9]
Hi, I would like to ask about function of the tool under icon - see attached printscreen of the Emotrics+, the icon in red square
When we click on, the score numbers change, but we don't know what exactly is the cause...

Thank you for your response!
Michaela

![IMG-20230711-WA0009](https://github.com/dguari1/Emotrics/assets/139802301/43b92357-2b01-437e-b2f6-6bcd29968e22)

**Comment by dguari1** [comment]
Hi @misaTes, that tool ensures that the pupils have the same diameter in all the images. So, you open the Resting Image and ensure that the pupils are correctly identified (manually adjust them if needed), then click on that button and the diameter will be replicated in all the other images. 
The pupil diameter is used to convert pixel distances to centimeters, so ensuring that all the images have the same diameter is important to guarantee consistency in the measurements

**Comment by misaTes** [comment]
Sorry for my late response - thank you!
